feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

client:
  organization-user-ms:
    name: organization-user-ms
    host: ${ORGANIZATION_USER_MS:http://localhost:8081}
    path: /organization-user-ms
